//
//  Country Lists.swift
//  FullMapGame
//
//  Created by Nick Melekian on 3/8/24.
//

import Foundation

let countryNames = ["Afghanistan",
                    "Albania",
                    "Algeria",
                    "Andorra",
                    "Angola",
                    "Anguilla",
                    "Antigua and Barbuda",
                    "Argentina",
                    "Armenia",
                    "Aruba",
                    "Australia",
                    "Austria",
                    "Azerbaijan",
                    "Bahamas",
                    "Bahrain",
                    "Bangladesh",
                    "Barbados",
                    "Belarus",
                    "Belgium",
                    "Belize",
                    "Benin",
                    "Bermuda",
                    "Bhutan",
                    "Bolivia",
                    "Bosnia and Herzegovina",
                    "Botswana",
                    "Brazil",
                    "Brunei",
                    "Bulgaria",
                    "Burkina Faso",
                    "Burundi",
                    "Cambodia",
                    "Cameroon",
                    "Canada",
                    "Cabo Verde",
                    "Cayman Islands",
                    "Central African Republic",
                    "Chad",
                    "Chile",
                    "China",
                    "Christmas Island",
                    "Colombia",
                    "Comoros",
                    "Cook Islands",
                    "Costa Rica",
                    "Croatia",
                    "Cuba",
                    "Cyprus",
                    "Czech Republic",
                    "Denmark",
                    "Djibouti",
                    "Dominica",
                    "Dominican Republic",
                    "East Timor",
                    "Ecuador",
                    "Egypt",
                    "El Salvador",
                    "Equatorial Guinea",
                    "Eritrea",
                    "Estonia",
                    "Ethiopia",
                    "Faroe Islands",
                    "Finland",
                    "France",
                    "French Guiana",
                    "Gabon",
                    "Gambia",
                    "Georgia",
                    "Germany",
                    "Ghana",
                    "Greece",
                    "Grenada",
                    "Guadeloupe",
                    "Guatemala",
                    "Guinea",
                    "Guinea-Bissau",
                    "Guyana",
                    "Haiti",
                    "Vatican City",
                    "Honduras",
                    "Hungary",
                    "Iceland",
                    "India",
                    "Indonesia",
                    "Iran",
                    "Iraq",
                    "Ireland",
                    "Israel",
                    "Italy",
                    "Ivory Coast",
                    "Jamaica",
                    "Japan",
                    "Jordan",
                    "Kazakhstan",
                    "Kenya",
                    "Kiribati",
                    "Kuwait",
                    "Kyrgyzstan",
                    "Laos",
                    "Latvia",
                    "Lebanon",
                    "Lesotho",
                    "Liberia",
                    "Liechtenstein",
                    "Lithuania",
                    "Luxembourg",
                    "North Macedonia",
                    "Madagascar",
                    "Malawi",
                    "Malaysia",
                    "Maldives",
                    "Mali",
                    "Malta",
                    "Marshall Islands",
                    "Martinique",
                    "Mauritania",
                    "Mauritius",
                    "Mexico",
                    "Federated States of Micronesia",
                    "Moldova",
                    "Monaco",
                    "Mongolia",
                    "Montenegro",
                    "Morocco",
                    "Mozambique",
                    "Myanmar",
                    "Namibia",
                    "Nauru",
                    "Nepal",
                    "Netherlands",
                    "New Zealand",
                    "Nicaragua",
                    "Niger",
                    "Nigeria",
                    "Niue",
                    "North Korea",
                    "Norway",
                    "Oman",
                    "Pakistan",
                    "Palau",
                    "Palestine",
                    "Panama",
                    "Papua New Guinea",
                    "Paraguay",
                    "Peru",
                    "Philippines",
                    "Poland",
                    "Portugal",
                    "Qatar",
                    "Reunion",
                    "Romania",
                    "Russia",
                    "Rwanda",
                    "Saint Kitts and Nevis",
                    "Saint Lucia",
                    "Saint Vincent and the Grenadines",
                    "Samoa",
                    "San Marino",
                    "Sao Tome and Principe",
                    "Saudi Arabia",
                    "Senegal",
                    "Serbia",
                    "Seychelles",
                    "Sierra Leone",
                    "Singapore",
                    "Slovakia",
                    "Slovenia",
                    "Solomon Islands",
                    "Somalia",
                    "South Africa",
                    "South Korea",
                    "South Sudan",
                    "Spain",
                    "Sri Lanka",
                    "Sudan",
                    "Suriname",
                    "Eswatini",
                    "Sweden",
                    "Switzerland",
                    "Syria",
                    "Taiwan",
                    "Tajikistan",
                    "Tanzania",
                    "Thailand",
                    "Democratic Republic of the Congo",
                    "Togo",
                    "Tonga",
                    "Trinidad and Tobago",
                    "Tunisia",
                    "Turkey",
                    "Turkmenistan",
                    "Turks and Caicos Islands",
                    "Tuvalu",
                    "Uganda",
                    "Ukraine",
                    "United Arab Emirates",
                    "United Kingdom",
                    "United States",
                    "Uruguay",
                    "Uzbekistan",
                    "Vanuatu",
                    "Venezuela",
                    "Vietnam",
                    "Western Sahara",
                    "Yemen",
                    "Zambia",
                    "Zimbabwe",
                    "Republic of the Congo"
]


let AfricaCountries = [
    "Morocco",
    "Algeria",
    "Tunisia",
    "Libya",
    "Egypt",
    "Mauritania",
    "Mali",
    "Niger",
    "Chad",
    "Sudan",
    "Eritrea",
    "Cabo Verde",
    "Senegal",
    "Gambia",
    "Guinea",
    "Guinea-Bissau",
    "Equatorial Guinea",
    "Sierra Leone",
    "Liberia",
    "Ivory Coast",
    "Ghana",
    "Burkina Faso",
    "Togo",
    "Benin",
    "Nigeria",
    "Cameroon",
    "Sao Tome and Principe",
    "Gabon",
    "Republic of the Congo",
    "Democratic Republic of the Congo",
    "Central African Republic",
    "Angola",
    "Namibia",
    "South Africa",
    "Lesotho",
    "Eswatini",
    "Botswana",
    "Zimbabwe",
    "Mozambique",
    "Malawi",
    "Zambia",
    "Tanzania",
    "Madagascar",
    "Mauritius",
    "Comoros",
    "Seychelles",
    "Rwanda",
    "Burundi",
    "Uganda",
    "Kenya",
    "Somalia",
    "Ethiopia",
    "Djibouti",
    "South Sudan",
    "Western Sahara"
]


let EuropeCountries = [
    "Iceland",
    "Ireland",
    "Portugal",
    "Spain",
    "Andorra",
    "Monaco",
    "France",
    "Switzerland",
    "Luxembourg",
    "Liechtenstein",
    "Belgium",
    "United Kingdom",
    "Netherlands",
    "Germany",
    "San Marino",
    "Italy",
    "Vatican City",
    "Malta",
    "Austria",
    "Czech Republic",
    "Denmark",
    "Slovakia",
    "Slovenia",
    "Croatia",
    "Norway",
    "Sweden",
    "Finland",
    "Russia",
    "Latvia",
    "Estonia",
    "Lithuania",
    "Poland",
    "Greece",
    "North Macedonia",
    "Serbia",
    "Montenegro",
    "Kosovo",
    "Bosnia and Herzegovina",
    "Albania",
    "Moldova",
    "Cyprus",
    "Turkey",
    "Hungary",
    "Romania",
    "Bulgaria",
    "Ukraine",
    "Belarus",
    "Faroe Islands"
]



let SouthAmericaCountries = [
    "Colombia",
    "Venezuela",
    "Ecuador",
    "Peru",
    "Chile",
    "Bolivia",
    "Paraguay",
    "Uruguay",
    "Argentina",
    "Brazil",
    "Guyana",
    "Suriname",
    "French Guiana"
]



let NorthAmericaCountries = [
    "Canada",
    "United States",
    "Mexico",
    "Guatemala",
    "Nicaragua",
    "Belize",
    "Honduras",
    "El Salvador",
    "Costa Rica",
    "Panama",
    "Cuba",
    "Haiti",
    "Dominica",
    "Dominican Republic",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Antigua and Barbuda",
    "Barbados",
    "Grenada",
    "Trinidad and Tobago",
    "Bahamas",
    "Jamaica",
    "Anguilla",
    "Aruba",
    "Bermuda",
    "Cayman Islands",
    "Guadeloupe",
    "Martinique",
    "Turks and Caicos Islands"
]



let AsianCountries = ["Afghanistan",
            "Armenia",
            "Azerbaijan",
            "Bahrain",
            "Bangladesh",
            "Bhutan",
            "Brunei",
            "Cambodia",
            "China",
            "Georgia",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Israel",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Lebanon",
            "Malaysia",
            "Mongolia",
            "Myanmar",
            "Nepal",
            "North Korea",
            "Oman",
            "Pakistan",
            "Palestine",
            "Philippines",
            "Qatar",
            "Reunion",
            "Saudi Arabia",
            "Singapore",
            "South Korea",
            "Sri Lanka",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Thailand",
            "Turkmenistan",
            "United Arab Emirates",
            "Uzbekistan",
            "Vietnam",
            "Yemen",
            "Maldives"]

let OceaniaCountries = ["Australia",
               "Christmas Island",
               "Cook Islands",
               "East Timor",
               "Kiribati",
               "Marshall Islands",
               "Federated States of Micronesia",
               "Nauru",
               "New Zealand",
               "Niue",
               "Palau",
               "Papua New Guinea",
               "Samoa",
               "Solomon Islands",
               "Tonga",
               "Tuvalu",
               "Vanuatu"]

let AmericanStatesDecode = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "GeorgiaState",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington DC",
    "Washington",
    "Wisconsin",
    "Wyoming"
]

let AmericanStates = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington DC",
    "Washington",
    "Wisconsin",
    "Wyoming"
]
